@startuml
interface Subject{
    + doSomething():void
}

class RealSubject

class InvocationHandler
class MyInvocationHandler

class Main
RealSubject .up.|> Subject
MyInvocationHandler .up.|> InvocationHandler

Main -up-> RealSubject
Main -up-> MyInvocationHandler

'RealSubject .up.|> Subject
'SubjectProxy .up.|> Subject
'SubjectProxy -right-> RealSubject
@enduml