@startuml
abstract class Creator{
    + FactoryMethod()
}
class ConcreteCreator
abstract class Product
class ConcreteProduct

ConcreteCreator -up-|> Creator
ConcreteProduct -up-|> Product
ConcreteCreator .left.> ConcreteProduct
@enduml
