@startuml
abstract class Builder{
    + setCpu():void
    + setRam():void
    + setDeviceId():void
    + setProductId():void
    + setSystemType():void
    + buildComputer():Computer
}

class LenovoBuilder{
    - computer :Computer
    + setCpu():void
    + setRam():void
    + setDeviceId():void
    + setProductId():void
    + setSystemType():void
    + buildComputer():Computer
}

class Computer{
    - deviceName
    - cpu
    - deviceId
    - productId
    - systemType
    + Computer(deviceName:String)
}

class Director{
    + makeComputer(builder:Builder):Computer
}

LenovoBuilder o.left. Computer
Director -right-o Builder
LenovoBuilder .up.|> Builder
@enduml